# Site settings
title:              An avenue of ways
email:              willem.ave@gmail.com
description:        >
  Musings on life, technology and audio.
baseurl:            "" # the subpath of your site, e.g. /blog/
url:                "http://willemsavenue.com" # the base hostname & protocol for your site
twitter_username:   willemaw
github_username:    willemave
date_format:        "%b %-d, %Y"

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Google analytics
google_analytics: UA-22360258-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Build settings
markdown:           kramdown
redcarpet:
  extensions:       ['smart', 'tables', 'with_toc_data']
permalink:          pretty
sass:
  compressed:       true

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-sass-converter

iawritercopier:
  src: '/Users/willem/Library/Mobile Documents/27N4MQEA55~pro~writer/Documents'
  categories:
  - blog
  - ideas
  - books

navigation:
  - text: 🏠
    url: /
  - text: 📖
    url: /books/
  - text: 👋
    url: /about/

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  per_page: 1000
  sort_reverse: true

