#!/bin/bash

set -ex

jekyll build

git add --all .

git commit -m 'Commit new content'

# if anything in the site/ subdirectory changed in the prior commit,
# push that directory to gh-pages for auto generation.
git diff-tree -r --name-only --no-commit-id master | grep '^_site/' &> /dev/null
if [ $? == 0 ]; then
  git push origin `git subtree split --prefix _site master 2> /dev/null`:gh-pages --force
fi

git reset HEAD~1

git clean -fdx _site
